import { blue, green, grey, orange, red, yellow } from "@libColors";
import { themeInitVariableRoot } from "@libTheme";

export let componentThemeRoot = themeInitVariableRoot(
  "lib-components",
  "UI Components Theme Variables",
  "Theme variables for UI components"
);

componentThemeRoot.makeVariable(
  "componentLabelTextColor",
  "componentLabelTextColor",
  "componentLabelTextColor",
  grey["700"],
  grey["300"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentBorderColor",
  "componentBorderColor",
  "componentBorderColor",
  grey["700"],
  grey["300"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentTextColor",
  "componentTextColor",
  "componentTextColor",
  grey["800"],
  grey["200"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentSymbolColor",
  "componentSymbolColor",
  "componentSymbolColor",
  grey["800"],
  grey["200"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentBackGroundColor",
  "componentBackGroundColor",
  "componentBackGroundColor",
  grey["50"],
  grey["900"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentHoverBackGroundColor",
  "componentHoverBackGroundColor",
  "componentHoverBackGroundColor",
  grey["400"],
  grey["700"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentFocusOutlineColor",
  "componentFocusOutlineColor",
  "componentFocusOutlineColor",
  orange["600"],
  orange["300"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentUnselectedBorderColor",
  "componentUnselectedBorderColor",
  "componentUnselectedBorderColor",
  grey["700"],
  grey["300"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentUnselectedTextColor",
  "componentUnselectedTextColor",
  "componentUnselectedTextColor",
  grey["600"],
  grey["400"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentUnselectedSymbolColor",
  "componentUnselectedSymbolColor",
  "componentUnselectedSymbolColor",
  grey["600"],
  grey["400"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentUnselectedBackGroundColor",
  "componentUnselectedBackGroundColor",
  "componentUnselectedBackGroundColor",
  grey["300"],
  grey["800"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentGreenColor",
  "componentGreenColor",
  "componentGreenColor",
  green["300"],
  green["900"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentRedColor",
  "componentRedColor",
  "componentRedColor",
  red["300"],
  red["900"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentBlueColor",
  "componentBlueColor",
  "componentBlueColor",
  blue["300"],
  blue["900"],
  "Color",
  undefined
);
componentThemeRoot.makeVariable(
  "componentYellowColor",
  "componentYellowColor",
  "componentYellowColor",
  yellow["300"],
  yellow["900"],
  "Color",
  undefined
);
